services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: stadipass-backend
    env_file:
      - .env
    ports:
      - "5001:5000"   # host:container (5001 on host, 5000 inside container)
    environment:
      PORT: "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
