name: Backend Docker CI

on:
  push:
    paths:
      - 'backend/**'
      - 'infra/docker/backend.Dockerfile'
      - '.github/workflows/backend-docker-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'infra/docker/backend.Dockerfile'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker (GH actions default)
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -f infra/docker/backend.Dockerfile \
            -t backend-ci-test \
            .

      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name backend-ci backend-ci-test
          sleep 10 # wait for server to start

      - name: Health check
        run: curl -f http://localhost:5000/health

      - name: Stop container
        if: always()
        run: docker stop backend-ci && docker rm backend-ci
